#!/bin/bash
set -e -x

cd "`dirname $0`"
export PYTHONPATH=".:`pwd`/src"

echo "==> Static Code Analysis for PEP8 style guide and various errors"
flake8 --statistics --count src/

if [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
    echo "==> Executing tests with code coverage collection"
    coverage run "src/proxymatic/test.py" $@
else
    python "src/proxymatic/test.py" $@
fi
